services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - data:/app/data
    stop_signal: SIGINT

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PROJECT_PATH}/data'
