"""empty message

Revision ID: 7ee86ff0f3d8
Revises: 79cdc7f41e4d
Create Date: 2022-07-02 21:53:30.593313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee86ff0f3d8'
down_revision = '79cdc7f41e4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyrogram_client_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyrogram_client_state')
    # ### end Alembic commands ###
