"""empty message

Revision ID: 059941c2cf2b
Revises: 8a71a959c034
Create Date: 2022-09-04 23:46:25.915574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059941c2cf2b'
down_revision = '8a71a959c034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_add_staff_tab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_in_window', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('current_input_field_index', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], name='fk_window_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_tab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_in_window', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('current_input_field_index', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], name='fk_window_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('add_staff_member_form_state')
    op.drop_table('group_user_tab')
    with op.batch_alter_table('tab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_input_field_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('window', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_class_crc32', sa.LargeBinary(length=4), nullable=False))
        batch_op.add_column(sa.Column('input_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('window', schema=None) as batch_op:
        batch_op.drop_column('input_required')
        batch_op.drop_column('window_class_crc32')

    with op.batch_alter_table('tab', schema=None) as batch_op:
        batch_op.drop_column('current_input_field_index')

    op.create_table('group_user_tab',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('index_in_window', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('window_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], name='fk_window_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_staff_member_form_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('current_state', sa.VARCHAR(), nullable=True),
    sa.Column('staff_type', sa.VARCHAR(length=9), nullable=True),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='unique_state')
    )
    op.drop_table('group_tab')
    op.drop_table('group_add_staff_tab')
    # ### end Alembic commands ###
