"""empty message

Revision ID: 79cdc7f41e4d
Revises: e92fcfcffd81
Create Date: 2022-07-02 21:22:33.014739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cdc7f41e4d'
down_revision = 'e92fcfcffd81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.LargeBinary(length=24), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('callback_name', sa.String(), nullable=True),
    sa.Column('arg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_data')
    )
    op.drop_table('button')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creation_date', sa.INTEGER(), nullable=True),
    sa.Column('callback_data', sa.VARCHAR(), nullable=True),
    sa.Column('callback_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('simple_button')
    # ### end Alembic commands ###
