"""empty message

Revision ID: 34ad592b83bd
Revises: a3beb6673254
Create Date: 2022-08-02 01:50:23.107898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ad592b83bd'
down_revision = 'a3beb6673254'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_staff_member_form_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(), nullable=True),
    sa.Column('staff_type', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='unique_state')
    )
    op.create_table('group_user_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.LargeBinary(length=20), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('callback_name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user_button')
    op.drop_table('add_staff_member_form_state')
    # ### end Alembic commands ###
