"""empty message

Revision ID: 52088bf4ff2d
Revises: 
Create Date: 2022-08-24 00:42:16.820309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52088bf4ff2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_staff_member_form_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(), nullable=True),
    sa.Column('staff_type', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='unique_state')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('remove_joins', sa.Boolean(), nullable=True),
    sa.Column('remove_leaves', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_user_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.LargeBinary(length=20), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('callback_name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_data')
    )
    op.create_table('simple_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.LargeBinary(length=20), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('callback_name', sa.String(), nullable=True),
    sa.Column('arg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_data')
    )
    op.create_table('simple_check_box_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.LargeBinary(length=20), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('unchecked_prefix', sa.String(), nullable=False),
    sa.Column('checked_prefix', sa.String(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('arg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_data')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_bind_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOIN', 'LEAVE', 'MESSAGE', name='eventtype'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_user_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('subscribed_to_mailings', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user_association')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('simple_check_box_button')
    op.drop_table('simple_button')
    op.drop_table('group_user_button')
    op.drop_table('group')
    op.drop_table('add_staff_member_form_state')
    # ### end Alembic commands ###
