"""empty message

Revision ID: a3beb6673254
Revises: 79cdc7f41e4d
Create Date: 2022-07-27 00:00:30.064640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3beb6673254'
down_revision = '79cdc7f41e4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_check_box_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.LargeBinary(length=20), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('unchecked_prefix', sa.String(), nullable=False),
    sa.Column('checked_prefix', sa.String(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('arg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_data')
    )
    op.create_table('group_user_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('subscribed_to_mailings', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.add_column('group', sa.Column('remove_joins', sa.Boolean(), nullable=True))
    op.add_column('group', sa.Column('remove_leaves', sa.Boolean(), nullable=True))
    op.drop_column('simple_button', 'button_id')
    op.add_column('user', sa.Column('group_bind_code', sa.String(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=9), nullable=False))
    op.drop_column('user', 'group_bind_code')
    op.add_column('simple_button', sa.Column('button_id', sa.INTEGER(), nullable=False))
    op.drop_column('group', 'remove_leaves')
    op.drop_column('group', 'remove_joins')
    op.drop_table('group_user_association')
    op.drop_table('simple_check_box_button')
    # ### end Alembic commands ###
