"""empty message

Revision ID: 6947c86b5385
Revises: 059941c2cf2b
Create Date: 2022-09-08 19:02:23.970326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6947c86b5385'
down_revision = '059941c2cf2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('input_field_text', sa.String(), nullable=True),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], name='fk_window_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    # ### end Alembic commands ###
