"""empty message

Revision ID: 6589985cc9bc
Revises: 6947c86b5385
Create Date: 2022-09-17 01:40:39.055139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6589985cc9bc'
down_revision = '6947c86b5385'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_stats_date_time_range_selection_tab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_in_window', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('current_input_field_index', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_date_time', sa.DateTime(), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.Column('screen', sa.Enum('START_DATE_TIME', 'END_DATE_TIME', name='groupstatsdatetimerangeselectionscreen'), nullable=True),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], name='fk_window_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_stats_tab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_in_window', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('current_input_field_index', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_date_time', sa.DateTime(), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['window_id'], ['window.id'], name='fk_window_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_box_button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    with op.batch_alter_table('simple_button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_button', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('check_box_button', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('group_stats_tab')
    op.drop_table('group_stats_date_time_range_selection_tab')
    # ### end Alembic commands ###
