"""Initial

Revision ID: 4dd12ecddeb1
Revises: 
Create Date: 2022-06-11 23:48:11.805177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd12ecddeb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Integer(), nullable=True),
    sa.Column('callback_data', sa.String(), nullable=True),
    sa.Column('callback_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('button')
    # ### end Alembic commands ###
