"""empty message

Revision ID: e09c7ced9a7d
Revises: 9665ff355168
Create Date: 2022-06-16 17:35:08.484736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09c7ced9a7d'
down_revision = '9665ff355168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'message_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('message_count', sa.INTEGER(), nullable=True))
    op.drop_table('group')
    # ### end Alembic commands ###
